/*!
 * LMV v7.52.0
 * 
 * Copyright 2021 Autodesk, Inc.
 * All rights reserved.
 * 
 * This computer source code and related instructions and comments are the
 * unpublished confidential and proprietary information of Autodesk, Inc.
 * and are protected under Federal copyright and state trade secret law.
 * They may not be disclosed to, copied or used by any third party without
 * the prior written consent of Autodesk, Inc.
 * 
 * Autodesk Forge Viewer Usage Limitations:
 * 
 * The Autodesk Forge viewer can only be used to view files generated by
 * Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be
 * delivered from an Autodesk hosted URL.
 */
Autodesk.Extensions.ExtensionsPanel =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./extensions/ExtensionsPanel/index.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./extensions/ExtensionsPanel/ExtensionListPanel.js":
/*!**********************************************************!*\
  !*** ./extensions/ExtensionsPanel/ExtensionListPanel.js ***!
  \**********************************************************/
/*! exports provided: ExtensionListPanel */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ExtensionListPanel", function() { return ExtensionListPanel; });
/* harmony import */ var _ExtensionSearchBox__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./ExtensionSearchBox */ "./extensions/ExtensionsPanel/ExtensionSearchBox.js");
function _typeof(obj) {"@babel/helpers - typeof";if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") {_typeof = function _typeof(obj) {return typeof obj;};} else {_typeof = function _typeof(obj) {return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;};}return _typeof(obj);}function _classCallCheck(instance, Constructor) {if (!(instance instanceof Constructor)) {throw new TypeError("Cannot call a class as a function");}}function _defineProperties(target, props) {for (var i = 0; i < props.length; i++) {var descriptor = props[i];descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if ("value" in descriptor) descriptor.writable = true;Object.defineProperty(target, descriptor.key, descriptor);}}function _createClass(Constructor, protoProps, staticProps) {if (protoProps) _defineProperties(Constructor.prototype, protoProps);if (staticProps) _defineProperties(Constructor, staticProps);return Constructor;}function _inherits(subClass, superClass) {if (typeof superClass !== "function" && superClass !== null) {throw new TypeError("Super expression must either be null or a function");}subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } });if (superClass) _setPrototypeOf(subClass, superClass);}function _setPrototypeOf(o, p) {_setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {o.__proto__ = p;return o;};return _setPrototypeOf(o, p);}function _createSuper(Derived) {var hasNativeReflectConstruct = _isNativeReflectConstruct();return function _createSuperInternal() {var Super = _getPrototypeOf(Derived),result;if (hasNativeReflectConstruct) {var NewTarget = _getPrototypeOf(this).constructor;result = Reflect.construct(Super, arguments, NewTarget);} else {result = Super.apply(this, arguments);}return _possibleConstructorReturn(this, result);};}function _possibleConstructorReturn(self, call) {if (call && (_typeof(call) === "object" || typeof call === "function")) {return call;}return _assertThisInitialized(self);}function _assertThisInitialized(self) {if (self === void 0) {throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return self;}function _isNativeReflectConstruct() {if (typeof Reflect === "undefined" || !Reflect.construct) return false;if (Reflect.construct.sham) return false;if (typeof Proxy === "function") return true;try {Date.prototype.toString.call(Reflect.construct(Date, [], function () {}));return true;} catch (e) {return false;}}function _getPrototypeOf(o) {_getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) {return o.__proto__ || Object.getPrototypeOf(o);};return _getPrototypeOf(o);}

var av = Autodesk.Viewing;
var SettingsPanel = av.UI.SettingsPanel;
var TAB_ID = "extensionsTab";
var TAB_LABEL = "Extensions";

/**
                               * @typedef {Object} registeredExtensions
                               * @property {string} id
                               * @property {boolean} inMemory
                               * @property {boolean} insync
                               */

var ExtensionListPanel = /*#__PURE__*/function (_Autodesk$Viewing$UI$) {_inherits(ExtensionListPanel, _Autodesk$Viewing$UI$);var _super = _createSuper(ExtensionListPanel);
  function ExtensionListPanel(viewer, viewerContainer, options) {var _this2;_classCallCheck(this, ExtensionListPanel);
    var PANEL_ID = "extension-list-panel";
    var PANEL_TITLE = Autodesk.Viewing.i18n.translate("Viewer Extensions List");
    _this2 = _super.call(this, viewerContainer, PANEL_ID, PANEL_TITLE, options);

    _this2.container.classList.add("extensions-panel");

    // Panel Settings
    _this2.addTab(TAB_ID, TAB_LABEL, { className: "extensions" });
    _this2.selectTab(TAB_ID);

    _this2.viewer = viewer;
    _this2.setGlobalManager(viewer.globalManager);

    _this2.getRegisteredExtensions = _this2.getRegisteredExtensions.bind(_assertThisInitialized(_this2));
    _this2.createExtensionsTableUI = _this2.createExtensionsTableUI.bind(_assertThisInitialized(_this2));
    _this2.addCheckbox = _this2.addCheckbox.bind(_assertThisInitialized(_this2));

    _this2.createExtensionsTableUI();

    _this2.searchbox = new _ExtensionSearchBox__WEBPACK_IMPORTED_MODULE_0__["ExtensionsListSearchBox"]("ExtensionSearch", {
      searchFunction: _this2.filterExtensions.bind(_assertThisInitialized(_this2)),
      displayAll: _this2.displayAll.bind(_assertThisInitialized(_this2)) });

    _this2.searchbox.setGlobalManager(_this2.globalManager);
    _this2.container.appendChild(_this2.searchbox.container);return _this2;
  }_createClass(ExtensionListPanel, [{ key: "displayAll", value: function displayAll()

    {
      var tableContainer = this.tablesContainer.firstChild;
      var extRows = tableContainer.getElementsByTagName("tr");
      extRows.forEach(function (e) {return e.style.display = "";});
    } }, { key: "filterExtensions", value: function filterExtensions(

    text) {
      var searchTerm = text.toLowerCase();

      var tableContainer = this.tablesContainer.firstChild;
      var extRows = tableContainer.getElementsByTagName("tr");

      var found = [];
      extRows.forEach(function (extnRow) {
        if (extnRow.innerText.toLowerCase().indexOf(searchTerm) !== -1) {
          found.push(extnRow.innerText);
          extnRow.style.display = "";
        } else {
          extnRow.style.display = "none";
        }
      });

      return found;
    } }, { key: "getRegisteredExtensions", value: function getRegisteredExtensions()

    {
      /** @type registeredExtensions[] */
      var registeredExtns = av.theExtensionManager.getRegisteredExtensions();
      // extract ids of registered extensions
      registeredExtns = registeredExtns.map(function (extensionData) {
        return extensionData.id;
      });

      return registeredExtns.sort();
    } }, { key: "createExtensionsTableUI", value: function createExtensionsTableUI()

    {
      var _this = this;
      var viewer = _this.viewer;
      _this.registeredExtns = this.getRegisteredExtensions();

      _this.registeredExtns.forEach(function (extObj) {
        _this.addCheckbox(TAB_ID, extObj, !!viewer.getExtension(extObj), function (checked) {
          if (checked) {
            var isLoaded = viewer.getExtension(extObj);
            if (!isLoaded) {
              viewer.loadExtension(extObj, viewer.config);
            }
          } else {
            viewer.unloadExtension(extObj);
          }
        });
      });

      _this.resizeToContent();
    } }, { key: "addCheckbox", value: function addCheckbox(

    tabId, name, initialState, onchange) {
      function onChangeCB(checked) {
        onchange && onchange(checked);
      }

      var checkboxId = SettingsPanel.prototype.addCheckbox.call(
      this,
      tabId,
      name,
      initialState,
      onChangeCB);


      return checkboxId;
    } }]);return ExtensionListPanel;}(Autodesk.Viewing.UI.SettingsPanel);

/***/ }),

/***/ "./extensions/ExtensionsPanel/ExtensionSearchBox.js":
/*!**********************************************************!*\
  !*** ./extensions/ExtensionsPanel/ExtensionSearchBox.js ***!
  \**********************************************************/
/*! exports provided: ExtensionsListSearchBox */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ExtensionsListSearchBox", function() { return ExtensionsListSearchBox; });
var debounce = __webpack_require__(/*! lodash/debounce */ "./node_modules/lodash/debounce.js");

function ExtensionsListSearchBox(id, options) {
  this._options = options;
  this._searchFunction = this._options.searchFunction || function () {};
  this._displayAll = this._options.displayAll || function () {};

  var _document = this.getDocument();
  this.container = _document.createElement("div");
  this.container.id = id;
  this.container.classList.add("adsk-control");
  this.container.classList.add("adsk-searchbox");
  this.container.classList.add("empty");

  var searchbox = _document.createElement("input");
  searchbox.classList.add("search-box");
  searchbox.classList.add("docking-panel-delimiter-shadow");
  searchbox.type = "search";
  searchbox.results = [];

  searchbox.addEventListener("input", function () {
    checkAndSearch(this); // delayed: as typing
  });

  searchbox.placeholder = Autodesk.Viewing.i18n.translate("Search");
  searchbox.setAttribute("data-i18n", "Search");

  this.container.appendChild(searchbox);
  this.searchbox = searchbox;

  var searchboxIcon = document.createElement("div");
  searchboxIcon.className = "search-box-icon";
  this.container.insertBefore(searchboxIcon, searchbox.nextSibling);

  var searchboxClose = document.createElement("div");
  searchboxClose.className = "search-box-close";
  searchboxClose.addEventListener("click", function () {
    clearSearchBox();
  });
  this.container.appendChild(searchboxClose);

  var noResultDiv = _document.createElement("div");
  noResultDiv.classList.add("no-results-container");
  noResultDiv.innerText = Autodesk.Viewing.i18n.translate("No results found");
  noResultDiv.style.display = "none";
  this.container.appendChild(noResultDiv);
  this.noResultDiv = noResultDiv;

  function clearSearchBox() {
    self.searchbox.value = "";
    self.container.classList.add("empty");
    self.searchbox.classList.remove("searching");
    showNoResultsDiv(false);
    self._displayAll();
  }

  function showNoResultsDiv(display) {
    self.noResultDiv.style.display = display ? "" : "none";
  }

  var self = this;

  var delayFor = 800;
  var checkAndSearch = debounce(function () {
    if (searchbox.value.length === 0) {
      self.container.classList.add("empty");
      showNoResultsDiv(false);
      self._displayAll();
      return;
    }

    self.container.classList.remove("empty");

    // prevent search while typing text that is too short.
    if (searchbox.value.length < 3) {
      return;
    }

    self.results = self._searchFunction(searchbox.value);
    showNoResultsDiv(!self.results.length);
  }, delayFor);
}

Autodesk.Viewing.GlobalManagerMixin.call(ExtensionsListSearchBox.prototype);

/***/ }),

/***/ "./extensions/ExtensionsPanel/ExtensionsPanel.scss":
/*!*********************************************************!*\
  !*** ./extensions/ExtensionsPanel/ExtensionsPanel.scss ***!
  \*********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../../node_modules/css-loader!../../node_modules/sass-loader/dist/cjs.js!./ExtensionsPanel.scss */ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/ExtensionsPanel/ExtensionsPanel.scss");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(false) {}

/***/ }),

/***/ "./extensions/ExtensionsPanel/ExtensionsPanelLocales.js":
/*!**************************************************************!*\
  !*** ./extensions/ExtensionsPanel/ExtensionsPanelLocales.js ***!
  \**************************************************************/
/*! exports provided: locales */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "locales", function() { return locales; });
/* harmony import */ var _res_locales_en_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../res/locales/en/nobundle-ExtensionsPanel.loc.json */ "./res/locales/en/nobundle-ExtensionsPanel.loc.json");
var _res_locales_en_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_0___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/en/nobundle-ExtensionsPanel.loc.json */ "./res/locales/en/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_en_GB_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../res/locales/en-GB/nobundle-ExtensionsPanel.loc.json */ "./res/locales/en-GB/nobundle-ExtensionsPanel.loc.json");
var _res_locales_en_GB_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_1___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/en-GB/nobundle-ExtensionsPanel.loc.json */ "./res/locales/en-GB/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_cs_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../res/locales/cs/nobundle-ExtensionsPanel.loc.json */ "./res/locales/cs/nobundle-ExtensionsPanel.loc.json");
var _res_locales_cs_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_2___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/cs/nobundle-ExtensionsPanel.loc.json */ "./res/locales/cs/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_de_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../res/locales/de/nobundle-ExtensionsPanel.loc.json */ "./res/locales/de/nobundle-ExtensionsPanel.loc.json");
var _res_locales_de_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_3___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/de/nobundle-ExtensionsPanel.loc.json */ "./res/locales/de/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_es_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../res/locales/es/nobundle-ExtensionsPanel.loc.json */ "./res/locales/es/nobundle-ExtensionsPanel.loc.json");
var _res_locales_es_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_4___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/es/nobundle-ExtensionsPanel.loc.json */ "./res/locales/es/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_fr_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../../res/locales/fr/nobundle-ExtensionsPanel.loc.json */ "./res/locales/fr/nobundle-ExtensionsPanel.loc.json");
var _res_locales_fr_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_5___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr/nobundle-ExtensionsPanel.loc.json */ "./res/locales/fr/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_fr_CA_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../../res/locales/fr-CA/nobundle-ExtensionsPanel.loc.json */ "./res/locales/fr-CA/nobundle-ExtensionsPanel.loc.json");
var _res_locales_fr_CA_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_6___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr-CA/nobundle-ExtensionsPanel.loc.json */ "./res/locales/fr-CA/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_it_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ../../res/locales/it/nobundle-ExtensionsPanel.loc.json */ "./res/locales/it/nobundle-ExtensionsPanel.loc.json");
var _res_locales_it_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_7___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/it/nobundle-ExtensionsPanel.loc.json */ "./res/locales/it/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_ja_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ../../res/locales/ja/nobundle-ExtensionsPanel.loc.json */ "./res/locales/ja/nobundle-ExtensionsPanel.loc.json");
var _res_locales_ja_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_8___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ja/nobundle-ExtensionsPanel.loc.json */ "./res/locales/ja/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_ko_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! ../../res/locales/ko/nobundle-ExtensionsPanel.loc.json */ "./res/locales/ko/nobundle-ExtensionsPanel.loc.json");
var _res_locales_ko_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_9___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ko/nobundle-ExtensionsPanel.loc.json */ "./res/locales/ko/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_pl_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ../../res/locales/pl/nobundle-ExtensionsPanel.loc.json */ "./res/locales/pl/nobundle-ExtensionsPanel.loc.json");
var _res_locales_pl_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_10___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pl/nobundle-ExtensionsPanel.loc.json */ "./res/locales/pl/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_pt_BR_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_11__ = __webpack_require__(/*! ../../res/locales/pt-BR/nobundle-ExtensionsPanel.loc.json */ "./res/locales/pt-BR/nobundle-ExtensionsPanel.loc.json");
var _res_locales_pt_BR_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_11___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pt-BR/nobundle-ExtensionsPanel.loc.json */ "./res/locales/pt-BR/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_ru_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_12__ = __webpack_require__(/*! ../../res/locales/ru/nobundle-ExtensionsPanel.loc.json */ "./res/locales/ru/nobundle-ExtensionsPanel.loc.json");
var _res_locales_ru_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_12___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ru/nobundle-ExtensionsPanel.loc.json */ "./res/locales/ru/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_tr_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_13__ = __webpack_require__(/*! ../../res/locales/tr/nobundle-ExtensionsPanel.loc.json */ "./res/locales/tr/nobundle-ExtensionsPanel.loc.json");
var _res_locales_tr_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_13___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/tr/nobundle-ExtensionsPanel.loc.json */ "./res/locales/tr/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANS_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_14__ = __webpack_require__(/*! ../../res/locales/zh-HANS/nobundle-ExtensionsPanel.loc.json */ "./res/locales/zh-HANS/nobundle-ExtensionsPanel.loc.json");
var _res_locales_zh_HANS_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_14___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANS/nobundle-ExtensionsPanel.loc.json */ "./res/locales/zh-HANS/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANT_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_15__ = __webpack_require__(/*! ../../res/locales/zh-HANT/nobundle-ExtensionsPanel.loc.json */ "./res/locales/zh-HANT/nobundle-ExtensionsPanel.loc.json");
var _res_locales_zh_HANT_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_15___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANT/nobundle-ExtensionsPanel.loc.json */ "./res/locales/zh-HANT/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_zh_HK_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_16__ = __webpack_require__(/*! ../../res/locales/zh-HK/nobundle-ExtensionsPanel.loc.json */ "./res/locales/zh-HK/nobundle-ExtensionsPanel.loc.json");
var _res_locales_zh_HK_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_16___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HK/nobundle-ExtensionsPanel.loc.json */ "./res/locales/zh-HK/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_nl_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_17__ = __webpack_require__(/*! ../../res/locales/nl/nobundle-ExtensionsPanel.loc.json */ "./res/locales/nl/nobundle-ExtensionsPanel.loc.json");
var _res_locales_nl_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_17___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/nl/nobundle-ExtensionsPanel.loc.json */ "./res/locales/nl/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_sv_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_18__ = __webpack_require__(/*! ../../res/locales/sv/nobundle-ExtensionsPanel.loc.json */ "./res/locales/sv/nobundle-ExtensionsPanel.loc.json");
var _res_locales_sv_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_18___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/sv/nobundle-ExtensionsPanel.loc.json */ "./res/locales/sv/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_da_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_19__ = __webpack_require__(/*! ../../res/locales/da/nobundle-ExtensionsPanel.loc.json */ "./res/locales/da/nobundle-ExtensionsPanel.loc.json");
var _res_locales_da_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_19___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/da/nobundle-ExtensionsPanel.loc.json */ "./res/locales/da/nobundle-ExtensionsPanel.loc.json", 1);
/* harmony import */ var _res_locales_no_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_20__ = __webpack_require__(/*! ../../res/locales/no/nobundle-ExtensionsPanel.loc.json */ "./res/locales/no/nobundle-ExtensionsPanel.loc.json");
var _res_locales_no_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_20___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/no/nobundle-ExtensionsPanel.loc.json */ "./res/locales/no/nobundle-ExtensionsPanel.loc.json", 1);
/**
 * Include each locale json file and return it in an object
 * that can be consumed by i18n
 */























var locales = {
  en: _res_locales_en_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_0__,
  "en-GB": _res_locales_en_GB_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_1__,
  cs: _res_locales_cs_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_2__,
  de: _res_locales_de_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_3__,
  es: _res_locales_es_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_4__,
  fr: _res_locales_fr_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_5__,
  "fr-CA": _res_locales_fr_CA_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_6__,
  it: _res_locales_it_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_7__,
  ja: _res_locales_ja_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_8__,
  ko: _res_locales_ko_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_9__,
  pl: _res_locales_pl_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_10__,
  "pt-BR": _res_locales_pt_BR_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_11__,
  ru: _res_locales_ru_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_12__,
  tr: _res_locales_tr_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_13__,
  "zh-HANS": _res_locales_zh_HANS_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_14__,
  "zh-HANT": _res_locales_zh_HANT_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_15__,
  "zh-HK": _res_locales_zh_HK_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_16__,
  nl: _res_locales_nl_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_17__,
  sv: _res_locales_sv_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_18__,
  da: _res_locales_da_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_19__,
  no: _res_locales_no_nobundle_ExtensionsPanel_loc_json__WEBPACK_IMPORTED_MODULE_20__ };

/***/ }),

/***/ "./extensions/ExtensionsPanel/index.js":
/*!*********************************************!*\
  !*** ./extensions/ExtensionsPanel/index.js ***!
  \*********************************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _ExtensionsPanel_scss__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./ExtensionsPanel.scss */ "./extensions/ExtensionsPanel/ExtensionsPanel.scss");
/* harmony import */ var _ExtensionsPanel_scss__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_ExtensionsPanel_scss__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var _ExtensionListPanel__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./ExtensionListPanel */ "./extensions/ExtensionsPanel/ExtensionListPanel.js");
/* harmony import */ var _ExtensionsPanelLocales__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./ExtensionsPanelLocales */ "./extensions/ExtensionsPanel/ExtensionsPanelLocales.js");
function _typeof(obj) {"@babel/helpers - typeof";if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") {_typeof = function _typeof(obj) {return typeof obj;};} else {_typeof = function _typeof(obj) {return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;};}return _typeof(obj);}function _classCallCheck(instance, Constructor) {if (!(instance instanceof Constructor)) {throw new TypeError("Cannot call a class as a function");}}function _defineProperties(target, props) {for (var i = 0; i < props.length; i++) {var descriptor = props[i];descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if ("value" in descriptor) descriptor.writable = true;Object.defineProperty(target, descriptor.key, descriptor);}}function _createClass(Constructor, protoProps, staticProps) {if (protoProps) _defineProperties(Constructor.prototype, protoProps);if (staticProps) _defineProperties(Constructor, staticProps);return Constructor;}function _inherits(subClass, superClass) {if (typeof superClass !== "function" && superClass !== null) {throw new TypeError("Super expression must either be null or a function");}subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } });if (superClass) _setPrototypeOf(subClass, superClass);}function _setPrototypeOf(o, p) {_setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {o.__proto__ = p;return o;};return _setPrototypeOf(o, p);}function _createSuper(Derived) {var hasNativeReflectConstruct = _isNativeReflectConstruct();return function _createSuperInternal() {var Super = _getPrototypeOf(Derived),result;if (hasNativeReflectConstruct) {var NewTarget = _getPrototypeOf(this).constructor;result = Reflect.construct(Super, arguments, NewTarget);} else {result = Super.apply(this, arguments);}return _possibleConstructorReturn(this, result);};}function _possibleConstructorReturn(self, call) {if (call && (_typeof(call) === "object" || typeof call === "function")) {return call;}return _assertThisInitialized(self);}function _assertThisInitialized(self) {if (self === void 0) {throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return self;}function _isNativeReflectConstruct() {if (typeof Reflect === "undefined" || !Reflect.construct) return false;if (Reflect.construct.sham) return false;if (typeof Proxy === "function") return true;try {Date.prototype.toString.call(Reflect.construct(Date, [], function () {}));return true;} catch (e) {return false;}}function _getPrototypeOf(o) {_getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) {return o.__proto__ || Object.getPrototypeOf(o);};return _getPrototypeOf(o);}


var av = Autodesk.Viewing;var

ExtensionsPanel = /*#__PURE__*/function (_Autodesk$Viewing$Ext) {_inherits(ExtensionsPanel, _Autodesk$Viewing$Ext);var _super = _createSuper(ExtensionsPanel);
  function ExtensionsPanel(viewer, options) {var _this;_classCallCheck(this, ExtensionsPanel);
    _this = _super.call(this, viewer, options);
    _this.panel = null;return _this;
  }_createClass(ExtensionsPanel, [{ key: "load", value: function load()

    {
      // Extend the localization strings
      this.extendLocalization(_ExtensionsPanelLocales__WEBPACK_IMPORTED_MODULE_2__["locales"]);

      if (this.viewer.toolbar) {
        // Toolbar is already available, create the UI
        this.createUI();
      } else {
        // Toolbar hasn't been created yet, wait until we get notification of its creation
        this.viewer.addEventListener(
        av.TOOLBAR_CREATED_EVENT,
        this._onToolbarCreated.bind(this));

      }
      return true;
    } }, { key: "unload", value: function unload()

    {
      if (this.subToolbar) {
        this.viewer.toolbar.removeControl(this.subToolbar);
        this.subToolbar = null;
      }
    } }, { key: "createUI", value: function createUI()

    {var _this2 = this;
      var panel = this.panel;

      // Panel already created, exit
      if (panel != null) {
        return;
      }

      // Create the Panel
      var options = { heightAdjustment: 144, width: 335, hideTabBar: true };
      this.panel = new _ExtensionListPanel__WEBPACK_IMPORTED_MODULE_1__["ExtensionListPanel"](this.viewer, this.viewer.container, options);

      // button to show the docking panel
      var showExtensionPanelButton = new av.UI.Button("ExtensionPanelBtn");
      showExtensionPanelButton.onClick = function (e) {
        this.panel.setVisible(!this.panel.isVisible());
      }.bind(this);

      showExtensionPanelButton.setIcon('adsk-icon-extn-showhide-button');
      showExtensionPanelButton.addClass("extn-showhide-button");
      showExtensionPanelButton.setToolTip("Load/Unload Extension");

      // SubToolbar
      this.subToolbar = new av.UI.ControlGroup("ExtensionsPanelToolbar");
      this.subToolbar.addControl(showExtensionPanelButton);

      this.viewer.toolbar.addControl(this.subToolbar);

      // Deactivate Button when docking panel is closed
      this.panel.addVisibilityListener(function (visible) {
        if (visible) {
          _this2.viewer.onPanelVisible(_this2.panel);
        }
        showExtensionPanelButton.setState(
        visible ? av.UI.Button.State.ACTIVE : av.UI.Button.State.INACTIVE);

      });
    } }, { key: "_onToolbarCreated", value: function _onToolbarCreated()

    {
      this.viewer.removeEventListener(av.TOOLBAR_CREATED_EVENT, this._onToolbarCreated);
      this.createUI();
    } }]);return ExtensionsPanel;}(Autodesk.Viewing.Extension);


Autodesk.Viewing.theExtensionManager.registerExtension("Autodesk.ExtensionsPanel", ExtensionsPanel);

/***/ }),

/***/ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/ExtensionsPanel/ExtensionsPanel.scss":
/*!**************************************************************************************************************************!*\
  !*** ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./extensions/ExtensionsPanel/ExtensionsPanel.scss ***!
  \**************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../../node_modules/css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, ".extn-showhide-button {\n  background-size: contain;\n  background-size: 80%;\n  background-repeat: no-repeat;\n  background-position: center; }\n\n.adsk-icon-extn-showhide-button:before {\n  content: \"1\"; }\n\n.extn-showhide-button .adsk-button-icon.adsk-icon-extn-showhide-button {\n  padding-top: 2px !important; }\n\n.adsk-viewing-viewer .extensions-panel {\n  border-radius: 0;\n  top: 15px;\n  left: 50%;\n  border-radius: 6px;\n  width: 340px;\n  height: 250px;\n  min-width: 250px;\n  min-height: 100px; }\n\n/* Scroller */\n.adsk-viewing-viewer .extensions-panel.docking-panel .docking-panel-scroll.right {\n  top: 34px !important; }\n\n/* Search */\n.adsk-viewing-viewer .adsk-searchbox {\n  top: 50px;\n  width: 100%;\n  position: absolute; }\n\n.no-results-container {\n  text-align: center;\n  padding-top: 20px;\n  padding-bottom: 20px;\n  font-weight: 600; }\n\n.adsk-viewing-viewer\n.extensions-panel.docking-panel\n.docking-panel-scroll.right\n.settings-tabs-tables-container\n.adsk-lmv-tftable\ntr.switch-slider-row\ntd {\n  padding: 8px;\n  height: 32px; }\n\n.adsk-viewing-viewer\n.extensions-panel.docking-panel\n.docking-panel-scroll.right\n.settings-tabs-tables-container\n.adsk-lmv-tftable\ntr.switch-slider-row\ntd:nth-child(2) {\n  width: 20px; }\n\n.adsk-viewing-viewer\n.extensions-panel.docking-panel\n.docking-panel-scroll.right\n.settings-tabs-tables-container\n.adsk-lmv-tftable\ntr.switch-slider-row\ntd:nth-child(1) {\n  width: 120px; }\n", ""]);

// exports


/***/ }),

/***/ "./node_modules/css-loader/lib/css-base.js":
/*!*************************************************!*\
  !*** ./node_modules/css-loader/lib/css-base.js ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
// css base code, injected by the css-loader
module.exports = function(useSourceMap) {
	var list = [];

	// return the list of modules as css string
	list.toString = function toString() {
		return this.map(function (item) {
			var content = cssWithMappingToString(item, useSourceMap);
			if(item[2]) {
				return "@media " + item[2] + "{" + content + "}";
			} else {
				return content;
			}
		}).join("");
	};

	// import a list of modules into the list
	list.i = function(modules, mediaQuery) {
		if(typeof modules === "string")
			modules = [[null, modules, ""]];
		var alreadyImportedModules = {};
		for(var i = 0; i < this.length; i++) {
			var id = this[i][0];
			if(typeof id === "number")
				alreadyImportedModules[id] = true;
		}
		for(i = 0; i < modules.length; i++) {
			var item = modules[i];
			// skip already imported module
			// this implementation is not 100% perfect for weird media query combinations
			//  when a module is imported multiple times with different media queries.
			//  I hope this will never occur (Hey this way we have smaller bundles)
			if(typeof item[0] !== "number" || !alreadyImportedModules[item[0]]) {
				if(mediaQuery && !item[2]) {
					item[2] = mediaQuery;
				} else if(mediaQuery) {
					item[2] = "(" + item[2] + ") and (" + mediaQuery + ")";
				}
				list.push(item);
			}
		}
	};
	return list;
};

function cssWithMappingToString(item, useSourceMap) {
	var content = item[1] || '';
	var cssMapping = item[3];
	if (!cssMapping) {
		return content;
	}

	if (useSourceMap && typeof btoa === 'function') {
		var sourceMapping = toComment(cssMapping);
		var sourceURLs = cssMapping.sources.map(function (source) {
			return '/*# sourceURL=' + cssMapping.sourceRoot + source + ' */'
		});

		return [content].concat(sourceURLs).concat([sourceMapping]).join('\n');
	}

	return [content].join('\n');
}

// Adapted from convert-source-map (MIT)
function toComment(sourceMap) {
	// eslint-disable-next-line no-undef
	var base64 = btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap))));
	var data = 'sourceMappingURL=data:application/json;charset=utf-8;base64,' + base64;

	return '/*# ' + data + ' */';
}


/***/ }),

/***/ "./node_modules/lodash/_Symbol.js":
/*!****************************************!*\
  !*** ./node_modules/lodash/_Symbol.js ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var root = __webpack_require__(/*! ./_root */ "./node_modules/lodash/_root.js");

/** Built-in value references. */
var Symbol = root.Symbol;

module.exports = Symbol;


/***/ }),

/***/ "./node_modules/lodash/_baseGetTag.js":
/*!********************************************!*\
  !*** ./node_modules/lodash/_baseGetTag.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var Symbol = __webpack_require__(/*! ./_Symbol */ "./node_modules/lodash/_Symbol.js"),
    getRawTag = __webpack_require__(/*! ./_getRawTag */ "./node_modules/lodash/_getRawTag.js"),
    objectToString = __webpack_require__(/*! ./_objectToString */ "./node_modules/lodash/_objectToString.js");

/** `Object#toString` result references. */
var nullTag = '[object Null]',
    undefinedTag = '[object Undefined]';

/** Built-in value references. */
var symToStringTag = Symbol ? Symbol.toStringTag : undefined;

/**
 * The base implementation of `getTag` without fallbacks for buggy environments.
 *
 * @private
 * @param {*} value The value to query.
 * @returns {string} Returns the `toStringTag`.
 */
function baseGetTag(value) {
  if (value == null) {
    return value === undefined ? undefinedTag : nullTag;
  }
  return (symToStringTag && symToStringTag in Object(value))
    ? getRawTag(value)
    : objectToString(value);
}

module.exports = baseGetTag;


/***/ }),

/***/ "./node_modules/lodash/_baseTrim.js":
/*!******************************************!*\
  !*** ./node_modules/lodash/_baseTrim.js ***!
  \******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var trimmedEndIndex = __webpack_require__(/*! ./_trimmedEndIndex */ "./node_modules/lodash/_trimmedEndIndex.js");

/** Used to match leading whitespace. */
var reTrimStart = /^\s+/;

/**
 * The base implementation of `_.trim`.
 *
 * @private
 * @param {string} string The string to trim.
 * @returns {string} Returns the trimmed string.
 */
function baseTrim(string) {
  return string
    ? string.slice(0, trimmedEndIndex(string) + 1).replace(reTrimStart, '')
    : string;
}

module.exports = baseTrim;


/***/ }),

/***/ "./node_modules/lodash/_freeGlobal.js":
/*!********************************************!*\
  !*** ./node_modules/lodash/_freeGlobal.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {/** Detect free variable `global` from Node.js. */
var freeGlobal = typeof global == 'object' && global && global.Object === Object && global;

module.exports = freeGlobal;

/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../webpack/buildin/global.js */ "./node_modules/webpack/buildin/global.js")))

/***/ }),

/***/ "./node_modules/lodash/_getRawTag.js":
/*!*******************************************!*\
  !*** ./node_modules/lodash/_getRawTag.js ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var Symbol = __webpack_require__(/*! ./_Symbol */ "./node_modules/lodash/_Symbol.js");

/** Used for built-in method references. */
var objectProto = Object.prototype;

/** Used to check objects for own properties. */
var hasOwnProperty = objectProto.hasOwnProperty;

/**
 * Used to resolve the
 * [`toStringTag`](http://ecma-international.org/ecma-262/7.0/#sec-object.prototype.tostring)
 * of values.
 */
var nativeObjectToString = objectProto.toString;

/** Built-in value references. */
var symToStringTag = Symbol ? Symbol.toStringTag : undefined;

/**
 * A specialized version of `baseGetTag` which ignores `Symbol.toStringTag` values.
 *
 * @private
 * @param {*} value The value to query.
 * @returns {string} Returns the raw `toStringTag`.
 */
function getRawTag(value) {
  var isOwn = hasOwnProperty.call(value, symToStringTag),
      tag = value[symToStringTag];

  try {
    value[symToStringTag] = undefined;
    var unmasked = true;
  } catch (e) {}

  var result = nativeObjectToString.call(value);
  if (unmasked) {
    if (isOwn) {
      value[symToStringTag] = tag;
    } else {
      delete value[symToStringTag];
    }
  }
  return result;
}

module.exports = getRawTag;


/***/ }),

/***/ "./node_modules/lodash/_objectToString.js":
/*!************************************************!*\
  !*** ./node_modules/lodash/_objectToString.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/** Used for built-in method references. */
var objectProto = Object.prototype;

/**
 * Used to resolve the
 * [`toStringTag`](http://ecma-international.org/ecma-262/7.0/#sec-object.prototype.tostring)
 * of values.
 */
var nativeObjectToString = objectProto.toString;

/**
 * Converts `value` to a string using `Object.prototype.toString`.
 *
 * @private
 * @param {*} value The value to convert.
 * @returns {string} Returns the converted string.
 */
function objectToString(value) {
  return nativeObjectToString.call(value);
}

module.exports = objectToString;


/***/ }),

/***/ "./node_modules/lodash/_root.js":
/*!**************************************!*\
  !*** ./node_modules/lodash/_root.js ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var freeGlobal = __webpack_require__(/*! ./_freeGlobal */ "./node_modules/lodash/_freeGlobal.js");

/** Detect free variable `self`. */
var freeSelf = typeof self == 'object' && self && self.Object === Object && self;

/** Used as a reference to the global object. */
var root = freeGlobal || freeSelf || Function('return this')();

module.exports = root;


/***/ }),

/***/ "./node_modules/lodash/_trimmedEndIndex.js":
/*!*************************************************!*\
  !*** ./node_modules/lodash/_trimmedEndIndex.js ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/** Used to match a single whitespace character. */
var reWhitespace = /\s/;

/**
 * Used by `_.trim` and `_.trimEnd` to get the index of the last non-whitespace
 * character of `string`.
 *
 * @private
 * @param {string} string The string to inspect.
 * @returns {number} Returns the index of the last non-whitespace character.
 */
function trimmedEndIndex(string) {
  var index = string.length;

  while (index-- && reWhitespace.test(string.charAt(index))) {}
  return index;
}

module.exports = trimmedEndIndex;


/***/ }),

/***/ "./node_modules/lodash/debounce.js":
/*!*****************************************!*\
  !*** ./node_modules/lodash/debounce.js ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var isObject = __webpack_require__(/*! ./isObject */ "./node_modules/lodash/isObject.js"),
    now = __webpack_require__(/*! ./now */ "./node_modules/lodash/now.js"),
    toNumber = __webpack_require__(/*! ./toNumber */ "./node_modules/lodash/toNumber.js");

/** Error message constants. */
var FUNC_ERROR_TEXT = 'Expected a function';

/* Built-in method references for those with the same name as other `lodash` methods. */
var nativeMax = Math.max,
    nativeMin = Math.min;

/**
 * Creates a debounced function that delays invoking `func` until after `wait`
 * milliseconds have elapsed since the last time the debounced function was
 * invoked. The debounced function comes with a `cancel` method to cancel
 * delayed `func` invocations and a `flush` method to immediately invoke them.
 * Provide `options` to indicate whether `func` should be invoked on the
 * leading and/or trailing edge of the `wait` timeout. The `func` is invoked
 * with the last arguments provided to the debounced function. Subsequent
 * calls to the debounced function return the result of the last `func`
 * invocation.
 *
 * **Note:** If `leading` and `trailing` options are `true`, `func` is
 * invoked on the trailing edge of the timeout only if the debounced function
 * is invoked more than once during the `wait` timeout.
 *
 * If `wait` is `0` and `leading` is `false`, `func` invocation is deferred
 * until to the next tick, similar to `setTimeout` with a timeout of `0`.
 *
 * See [David Corbacho's article](https://css-tricks.com/debouncing-throttling-explained-examples/)
 * for details over the differences between `_.debounce` and `_.throttle`.
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Function
 * @param {Function} func The function to debounce.
 * @param {number} [wait=0] The number of milliseconds to delay.
 * @param {Object} [options={}] The options object.
 * @param {boolean} [options.leading=false]
 *  Specify invoking on the leading edge of the timeout.
 * @param {number} [options.maxWait]
 *  The maximum time `func` is allowed to be delayed before it's invoked.
 * @param {boolean} [options.trailing=true]
 *  Specify invoking on the trailing edge of the timeout.
 * @returns {Function} Returns the new debounced function.
 * @example
 *
 * // Avoid costly calculations while the window size is in flux.
 * jQuery(window).on('resize', _.debounce(calculateLayout, 150));
 *
 * // Invoke `sendMail` when clicked, debouncing subsequent calls.
 * jQuery(element).on('click', _.debounce(sendMail, 300, {
 *   'leading': true,
 *   'trailing': false
 * }));
 *
 * // Ensure `batchLog` is invoked once after 1 second of debounced calls.
 * var debounced = _.debounce(batchLog, 250, { 'maxWait': 1000 });
 * var source = new EventSource('/stream');
 * jQuery(source).on('message', debounced);
 *
 * // Cancel the trailing debounced invocation.
 * jQuery(window).on('popstate', debounced.cancel);
 */
function debounce(func, wait, options) {
  var lastArgs,
      lastThis,
      maxWait,
      result,
      timerId,
      lastCallTime,
      lastInvokeTime = 0,
      leading = false,
      maxing = false,
      trailing = true;

  if (typeof func != 'function') {
    throw new TypeError(FUNC_ERROR_TEXT);
  }
  wait = toNumber(wait) || 0;
  if (isObject(options)) {
    leading = !!options.leading;
    maxing = 'maxWait' in options;
    maxWait = maxing ? nativeMax(toNumber(options.maxWait) || 0, wait) : maxWait;
    trailing = 'trailing' in options ? !!options.trailing : trailing;
  }

  function invokeFunc(time) {
    var args = lastArgs,
        thisArg = lastThis;

    lastArgs = lastThis = undefined;
    lastInvokeTime = time;
    result = func.apply(thisArg, args);
    return result;
  }

  function leadingEdge(time) {
    // Reset any `maxWait` timer.
    lastInvokeTime = time;
    // Start the timer for the trailing edge.
    timerId = setTimeout(timerExpired, wait);
    // Invoke the leading edge.
    return leading ? invokeFunc(time) : result;
  }

  function remainingWait(time) {
    var timeSinceLastCall = time - lastCallTime,
        timeSinceLastInvoke = time - lastInvokeTime,
        timeWaiting = wait - timeSinceLastCall;

    return maxing
      ? nativeMin(timeWaiting, maxWait - timeSinceLastInvoke)
      : timeWaiting;
  }

  function shouldInvoke(time) {
    var timeSinceLastCall = time - lastCallTime,
        timeSinceLastInvoke = time - lastInvokeTime;

    // Either this is the first call, activity has stopped and we're at the
    // trailing edge, the system time has gone backwards and we're treating
    // it as the trailing edge, or we've hit the `maxWait` limit.
    return (lastCallTime === undefined || (timeSinceLastCall >= wait) ||
      (timeSinceLastCall < 0) || (maxing && timeSinceLastInvoke >= maxWait));
  }

  function timerExpired() {
    var time = now();
    if (shouldInvoke(time)) {
      return trailingEdge(time);
    }
    // Restart the timer.
    timerId = setTimeout(timerExpired, remainingWait(time));
  }

  function trailingEdge(time) {
    timerId = undefined;

    // Only invoke if we have `lastArgs` which means `func` has been
    // debounced at least once.
    if (trailing && lastArgs) {
      return invokeFunc(time);
    }
    lastArgs = lastThis = undefined;
    return result;
  }

  function cancel() {
    if (timerId !== undefined) {
      clearTimeout(timerId);
    }
    lastInvokeTime = 0;
    lastArgs = lastCallTime = lastThis = timerId = undefined;
  }

  function flush() {
    return timerId === undefined ? result : trailingEdge(now());
  }

  function debounced() {
    var time = now(),
        isInvoking = shouldInvoke(time);

    lastArgs = arguments;
    lastThis = this;
    lastCallTime = time;

    if (isInvoking) {
      if (timerId === undefined) {
        return leadingEdge(lastCallTime);
      }
      if (maxing) {
        // Handle invocations in a tight loop.
        clearTimeout(timerId);
        timerId = setTimeout(timerExpired, wait);
        return invokeFunc(lastCallTime);
      }
    }
    if (timerId === undefined) {
      timerId = setTimeout(timerExpired, wait);
    }
    return result;
  }
  debounced.cancel = cancel;
  debounced.flush = flush;
  return debounced;
}

module.exports = debounce;


/***/ }),

/***/ "./node_modules/lodash/isObject.js":
/*!*****************************************!*\
  !*** ./node_modules/lodash/isObject.js ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/**
 * Checks if `value` is the
 * [language type](http://www.ecma-international.org/ecma-262/7.0/#sec-ecmascript-language-types)
 * of `Object`. (e.g. arrays, functions, objects, regexes, `new Number(0)`, and `new String('')`)
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is an object, else `false`.
 * @example
 *
 * _.isObject({});
 * // => true
 *
 * _.isObject([1, 2, 3]);
 * // => true
 *
 * _.isObject(_.noop);
 * // => true
 *
 * _.isObject(null);
 * // => false
 */
function isObject(value) {
  var type = typeof value;
  return value != null && (type == 'object' || type == 'function');
}

module.exports = isObject;


/***/ }),

/***/ "./node_modules/lodash/isObjectLike.js":
/*!*********************************************!*\
  !*** ./node_modules/lodash/isObjectLike.js ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/**
 * Checks if `value` is object-like. A value is object-like if it's not `null`
 * and has a `typeof` result of "object".
 *
 * @static
 * @memberOf _
 * @since 4.0.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is object-like, else `false`.
 * @example
 *
 * _.isObjectLike({});
 * // => true
 *
 * _.isObjectLike([1, 2, 3]);
 * // => true
 *
 * _.isObjectLike(_.noop);
 * // => false
 *
 * _.isObjectLike(null);
 * // => false
 */
function isObjectLike(value) {
  return value != null && typeof value == 'object';
}

module.exports = isObjectLike;


/***/ }),

/***/ "./node_modules/lodash/isSymbol.js":
/*!*****************************************!*\
  !*** ./node_modules/lodash/isSymbol.js ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var baseGetTag = __webpack_require__(/*! ./_baseGetTag */ "./node_modules/lodash/_baseGetTag.js"),
    isObjectLike = __webpack_require__(/*! ./isObjectLike */ "./node_modules/lodash/isObjectLike.js");

/** `Object#toString` result references. */
var symbolTag = '[object Symbol]';

/**
 * Checks if `value` is classified as a `Symbol` primitive or object.
 *
 * @static
 * @memberOf _
 * @since 4.0.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is a symbol, else `false`.
 * @example
 *
 * _.isSymbol(Symbol.iterator);
 * // => true
 *
 * _.isSymbol('abc');
 * // => false
 */
function isSymbol(value) {
  return typeof value == 'symbol' ||
    (isObjectLike(value) && baseGetTag(value) == symbolTag);
}

module.exports = isSymbol;


/***/ }),

/***/ "./node_modules/lodash/now.js":
/*!************************************!*\
  !*** ./node_modules/lodash/now.js ***!
  \************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var root = __webpack_require__(/*! ./_root */ "./node_modules/lodash/_root.js");

/**
 * Gets the timestamp of the number of milliseconds that have elapsed since
 * the Unix epoch (1 January 1970 00:00:00 UTC).
 *
 * @static
 * @memberOf _
 * @since 2.4.0
 * @category Date
 * @returns {number} Returns the timestamp.
 * @example
 *
 * _.defer(function(stamp) {
 *   console.log(_.now() - stamp);
 * }, _.now());
 * // => Logs the number of milliseconds it took for the deferred invocation.
 */
var now = function() {
  return root.Date.now();
};

module.exports = now;


/***/ }),

/***/ "./node_modules/lodash/toNumber.js":
/*!*****************************************!*\
  !*** ./node_modules/lodash/toNumber.js ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var baseTrim = __webpack_require__(/*! ./_baseTrim */ "./node_modules/lodash/_baseTrim.js"),
    isObject = __webpack_require__(/*! ./isObject */ "./node_modules/lodash/isObject.js"),
    isSymbol = __webpack_require__(/*! ./isSymbol */ "./node_modules/lodash/isSymbol.js");

/** Used as references for various `Number` constants. */
var NAN = 0 / 0;

/** Used to detect bad signed hexadecimal string values. */
var reIsBadHex = /^[-+]0x[0-9a-f]+$/i;

/** Used to detect binary string values. */
var reIsBinary = /^0b[01]+$/i;

/** Used to detect octal string values. */
var reIsOctal = /^0o[0-7]+$/i;

/** Built-in method references without a dependency on `root`. */
var freeParseInt = parseInt;

/**
 * Converts `value` to a number.
 *
 * @static
 * @memberOf _
 * @since 4.0.0
 * @category Lang
 * @param {*} value The value to process.
 * @returns {number} Returns the number.
 * @example
 *
 * _.toNumber(3.2);
 * // => 3.2
 *
 * _.toNumber(Number.MIN_VALUE);
 * // => 5e-324
 *
 * _.toNumber(Infinity);
 * // => Infinity
 *
 * _.toNumber('3.2');
 * // => 3.2
 */
function toNumber(value) {
  if (typeof value == 'number') {
    return value;
  }
  if (isSymbol(value)) {
    return NAN;
  }
  if (isObject(value)) {
    var other = typeof value.valueOf == 'function' ? value.valueOf() : value;
    value = isObject(other) ? (other + '') : other;
  }
  if (typeof value != 'string') {
    return value === 0 ? value : +value;
  }
  value = baseTrim(value);
  var isBinary = reIsBinary.test(value);
  return (isBinary || reIsOctal.test(value))
    ? freeParseInt(value.slice(2), isBinary ? 2 : 8)
    : (reIsBadHex.test(value) ? NAN : +value);
}

module.exports = toNumber;


/***/ }),

/***/ "./node_modules/style-loader/lib/addStyles.js":
/*!****************************************************!*\
  !*** ./node_modules/style-loader/lib/addStyles.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

var stylesInDom = {};

var	memoize = function (fn) {
	var memo;

	return function () {
		if (typeof memo === "undefined") memo = fn.apply(this, arguments);
		return memo;
	};
};

var isOldIE = memoize(function () {
	// Test for IE <= 9 as proposed by Browserhacks
	// @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
	// Tests for existence of standard globals is to allow style-loader
	// to operate correctly into non-standard environments
	// @see https://github.com/webpack-contrib/style-loader/issues/177
	return window && document && document.all && !window.atob;
});

var getTarget = function (target, parent) {
  if (parent){
    return parent.querySelector(target);
  }
  return document.querySelector(target);
};

var getElement = (function (fn) {
	var memo = {};

	return function(target, parent) {
                // If passing function in options, then use it for resolve "head" element.
                // Useful for Shadow Root style i.e
                // {
                //   insertInto: function () { return document.querySelector("#foo").shadowRoot }
                // }
                if (typeof target === 'function') {
                        return target();
                }
                if (typeof memo[target] === "undefined") {
			var styleTarget = getTarget.call(this, target, parent);
			// Special case to return head of iframe instead of iframe itself
			if (window.HTMLIFrameElement && styleTarget instanceof window.HTMLIFrameElement) {
				try {
					// This will throw an exception if access to iframe is blocked
					// due to cross-origin restrictions
					styleTarget = styleTarget.contentDocument.head;
				} catch(e) {
					styleTarget = null;
				}
			}
			memo[target] = styleTarget;
		}
		return memo[target]
	};
})();

var singleton = null;
var	singletonCounter = 0;
var	stylesInsertedAtTop = [];

var	fixUrls = __webpack_require__(/*! ./urls */ "./node_modules/style-loader/lib/urls.js");

module.exports = function(list, options) {
	if (typeof DEBUG !== "undefined" && DEBUG) {
		if (typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
	}

	options = options || {};

	options.attrs = typeof options.attrs === "object" ? options.attrs : {};

	// Force single-tag solution on IE6-9, which has a hard limit on the # of <style>
	// tags it will allow on a page
	if (!options.singleton && typeof options.singleton !== "boolean") options.singleton = isOldIE();

	// By default, add <style> tags to the <head> element
        if (!options.insertInto) options.insertInto = "head";

	// By default, add <style> tags to the bottom of the target
	if (!options.insertAt) options.insertAt = "bottom";

	var styles = listToStyles(list, options);

	addStylesToDom(styles, options);

	return function update (newList) {
		var mayRemove = [];

		for (var i = 0; i < styles.length; i++) {
			var item = styles[i];
			var domStyle = stylesInDom[item.id];

			domStyle.refs--;
			mayRemove.push(domStyle);
		}

		if(newList) {
			var newStyles = listToStyles(newList, options);
			addStylesToDom(newStyles, options);
		}

		for (var i = 0; i < mayRemove.length; i++) {
			var domStyle = mayRemove[i];

			if(domStyle.refs === 0) {
				for (var j = 0; j < domStyle.parts.length; j++) domStyle.parts[j]();

				delete stylesInDom[domStyle.id];
			}
		}
	};
};

function addStylesToDom (styles, options) {
	for (var i = 0; i < styles.length; i++) {
		var item = styles[i];
		var domStyle = stylesInDom[item.id];

		if(domStyle) {
			domStyle.refs++;

			for(var j = 0; j < domStyle.parts.length; j++) {
				domStyle.parts[j](item.parts[j]);
			}

			for(; j < item.parts.length; j++) {
				domStyle.parts.push(addStyle(item.parts[j], options));
			}
		} else {
			var parts = [];

			for(var j = 0; j < item.parts.length; j++) {
				parts.push(addStyle(item.parts[j], options));
			}

			stylesInDom[item.id] = {id: item.id, refs: 1, parts: parts};
		}
	}
}

function listToStyles (list, options) {
	var styles = [];
	var newStyles = {};

	for (var i = 0; i < list.length; i++) {
		var item = list[i];
		var id = options.base ? item[0] + options.base : item[0];
		var css = item[1];
		var media = item[2];
		var sourceMap = item[3];
		var part = {css: css, media: media, sourceMap: sourceMap};

		if(!newStyles[id]) styles.push(newStyles[id] = {id: id, parts: [part]});
		else newStyles[id].parts.push(part);
	}

	return styles;
}

function insertStyleElement (options, style) {
	var target = getElement(options.insertInto)

	if (!target) {
		throw new Error("Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.");
	}

	var lastStyleElementInsertedAtTop = stylesInsertedAtTop[stylesInsertedAtTop.length - 1];

	if (options.insertAt === "top") {
		if (!lastStyleElementInsertedAtTop) {
			target.insertBefore(style, target.firstChild);
		} else if (lastStyleElementInsertedAtTop.nextSibling) {
			target.insertBefore(style, lastStyleElementInsertedAtTop.nextSibling);
		} else {
			target.appendChild(style);
		}
		stylesInsertedAtTop.push(style);
	} else if (options.insertAt === "bottom") {
		target.appendChild(style);
	} else if (typeof options.insertAt === "object" && options.insertAt.before) {
		var nextSibling = getElement(options.insertAt.before, target);
		target.insertBefore(style, nextSibling);
	} else {
		throw new Error("[Style Loader]\n\n Invalid value for parameter 'insertAt' ('options.insertAt') found.\n Must be 'top', 'bottom', or Object.\n (https://github.com/webpack-contrib/style-loader#insertat)\n");
	}
}

function removeStyleElement (style) {
	if (style.parentNode === null) return false;
	style.parentNode.removeChild(style);

	var idx = stylesInsertedAtTop.indexOf(style);
	if(idx >= 0) {
		stylesInsertedAtTop.splice(idx, 1);
	}
}

function createStyleElement (options) {
	var style = document.createElement("style");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}

	if(options.attrs.nonce === undefined) {
		var nonce = getNonce();
		if (nonce) {
			options.attrs.nonce = nonce;
		}
	}

	addAttrs(style, options.attrs);
	insertStyleElement(options, style);

	return style;
}

function createLinkElement (options) {
	var link = document.createElement("link");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}
	options.attrs.rel = "stylesheet";

	addAttrs(link, options.attrs);
	insertStyleElement(options, link);

	return link;
}

function addAttrs (el, attrs) {
	Object.keys(attrs).forEach(function (key) {
		el.setAttribute(key, attrs[key]);
	});
}

function getNonce() {
	if (false) {}

	return __webpack_require__.nc;
}

function addStyle (obj, options) {
	var style, update, remove, result;

	// If a transform function was defined, run it on the css
	if (options.transform && obj.css) {
	    result = typeof options.transform === 'function'
		 ? options.transform(obj.css) 
		 : options.transform.default(obj.css);

	    if (result) {
	    	// If transform returns a value, use that instead of the original css.
	    	// This allows running runtime transformations on the css.
	    	obj.css = result;
	    } else {
	    	// If the transform function returns a falsy value, don't add this css.
	    	// This allows conditional loading of css
	    	return function() {
	    		// noop
	    	};
	    }
	}

	if (options.singleton) {
		var styleIndex = singletonCounter++;

		style = singleton || (singleton = createStyleElement(options));

		update = applyToSingletonTag.bind(null, style, styleIndex, false);
		remove = applyToSingletonTag.bind(null, style, styleIndex, true);

	} else if (
		obj.sourceMap &&
		typeof URL === "function" &&
		typeof URL.createObjectURL === "function" &&
		typeof URL.revokeObjectURL === "function" &&
		typeof Blob === "function" &&
		typeof btoa === "function"
	) {
		style = createLinkElement(options);
		update = updateLink.bind(null, style, options);
		remove = function () {
			removeStyleElement(style);

			if(style.href) URL.revokeObjectURL(style.href);
		};
	} else {
		style = createStyleElement(options);
		update = applyToTag.bind(null, style);
		remove = function () {
			removeStyleElement(style);
		};
	}

	update(obj);

	return function updateStyle (newObj) {
		if (newObj) {
			if (
				newObj.css === obj.css &&
				newObj.media === obj.media &&
				newObj.sourceMap === obj.sourceMap
			) {
				return;
			}

			update(obj = newObj);
		} else {
			remove();
		}
	};
}

var replaceText = (function () {
	var textStore = [];

	return function (index, replacement) {
		textStore[index] = replacement;

		return textStore.filter(Boolean).join('\n');
	};
})();

function applyToSingletonTag (style, index, remove, obj) {
	var css = remove ? "" : obj.css;

	if (style.styleSheet) {
		style.styleSheet.cssText = replaceText(index, css);
	} else {
		var cssNode = document.createTextNode(css);
		var childNodes = style.childNodes;

		if (childNodes[index]) style.removeChild(childNodes[index]);

		if (childNodes.length) {
			style.insertBefore(cssNode, childNodes[index]);
		} else {
			style.appendChild(cssNode);
		}
	}
}

function applyToTag (style, obj) {
	var css = obj.css;
	var media = obj.media;

	if(media) {
		style.setAttribute("media", media)
	}

	if(style.styleSheet) {
		style.styleSheet.cssText = css;
	} else {
		while(style.firstChild) {
			style.removeChild(style.firstChild);
		}

		style.appendChild(document.createTextNode(css));
	}
}

function updateLink (link, options, obj) {
	var css = obj.css;
	var sourceMap = obj.sourceMap;

	/*
		If convertToAbsoluteUrls isn't defined, but sourcemaps are enabled
		and there is no publicPath defined then lets turn convertToAbsoluteUrls
		on by default.  Otherwise default to the convertToAbsoluteUrls option
		directly
	*/
	var autoFixUrls = options.convertToAbsoluteUrls === undefined && sourceMap;

	if (options.convertToAbsoluteUrls || autoFixUrls) {
		css = fixUrls(css);
	}

	if (sourceMap) {
		// http://stackoverflow.com/a/26603875
		css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
	}

	var blob = new Blob([css], { type: "text/css" });

	var oldSrc = link.href;

	link.href = URL.createObjectURL(blob);

	if(oldSrc) URL.revokeObjectURL(oldSrc);
}


/***/ }),

/***/ "./node_modules/style-loader/lib/urls.js":
/*!***********************************************!*\
  !*** ./node_modules/style-loader/lib/urls.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports) {


/**
 * When source maps are enabled, `style-loader` uses a link element with a data-uri to
 * embed the css on the page. This breaks all relative urls because now they are relative to a
 * bundle instead of the current page.
 *
 * One solution is to only use full urls, but that may be impossible.
 *
 * Instead, this function "fixes" the relative urls to be absolute according to the current page location.
 *
 * A rudimentary test suite is located at `test/fixUrls.js` and can be run via the `npm test` command.
 *
 */

module.exports = function (css) {
  // get current location
  var location = typeof window !== "undefined" && window.location;

  if (!location) {
    throw new Error("fixUrls requires window.location");
  }

	// blank or null?
	if (!css || typeof css !== "string") {
	  return css;
  }

  var baseUrl = location.protocol + "//" + location.host;
  var currentDir = baseUrl + location.pathname.replace(/\/[^\/]*$/, "/");

	// convert each url(...)
	/*
	This regular expression is just a way to recursively match brackets within
	a string.

	 /url\s*\(  = Match on the word "url" with any whitespace after it and then a parens
	   (  = Start a capturing group
	     (?:  = Start a non-capturing group
	         [^)(]  = Match anything that isn't a parentheses
	         |  = OR
	         \(  = Match a start parentheses
	             (?:  = Start another non-capturing groups
	                 [^)(]+  = Match anything that isn't a parentheses
	                 |  = OR
	                 \(  = Match a start parentheses
	                     [^)(]*  = Match anything that isn't a parentheses
	                 \)  = Match a end parentheses
	             )  = End Group
              *\) = Match anything and then a close parens
          )  = Close non-capturing group
          *  = Match anything
       )  = Close capturing group
	 \)  = Match a close parens

	 /gi  = Get all matches, not the first.  Be case insensitive.
	 */
	var fixedCss = css.replace(/url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)/gi, function(fullMatch, origUrl) {
		// strip quotes (if they exist)
		var unquotedOrigUrl = origUrl
			.trim()
			.replace(/^"(.*)"$/, function(o, $1){ return $1; })
			.replace(/^'(.*)'$/, function(o, $1){ return $1; });

		// already a full url? no change
		if (/^(#|data:|http:\/\/|https:\/\/|file:\/\/\/|\s*$)/i.test(unquotedOrigUrl)) {
		  return fullMatch;
		}

		// convert the url to a full url
		var newUrl;

		if (unquotedOrigUrl.indexOf("//") === 0) {
		  	//TODO: should we add protocol?
			newUrl = unquotedOrigUrl;
		} else if (unquotedOrigUrl.indexOf("/") === 0) {
			// path should be relative to the base url
			newUrl = baseUrl + unquotedOrigUrl; // already starts with '/'
		} else {
			// path should be relative to current directory
			newUrl = currentDir + unquotedOrigUrl.replace(/^\.\//, ""); // Strip leading './'
		}

		// send back the fixed url(...)
		return "url(" + JSON.stringify(newUrl) + ")";
	});

	// send back the fixed css
	return fixedCss;
};


/***/ }),

/***/ "./node_modules/webpack/buildin/global.js":
/*!***********************************!*\
  !*** (webpack)/buildin/global.js ***!
  \***********************************/
/*! no static exports found */
/***/ (function(module, exports) {

var g;

// This works in non-strict mode
g = (function() {
	return this;
})();

try {
	// This works if eval is allowed (see CSP)
	g = g || new Function("return this")();
} catch (e) {
	// This works if the window reference is available
	if (typeof window === "object") g = window;
}

// g can still be undefined, but nothing to do about it...
// We return undefined, instead of nothing here, so it's
// easier to handle this case. if(!global) { ...}

module.exports = g;


/***/ }),

/***/ "./res/locales/cs/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/cs/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"cs\",\"@@context\":\"Rozšíření ExtensionsPanel\",\"Viewer Extensions List\":\"Seznam rozšíření prohlížeče\",\"Search\":\"Hledat\",\"No results found\":\"Nebyly nalezeny žádné výsledky\"}");

/***/ }),

/***/ "./res/locales/da/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/da/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"da\",\"@@context\":\"UdvidelserPaneludvidelse\",\"Viewer Extensions List\":\"Liste over fremviserudvidelser\",\"Search\":\"Søg\",\"No results found\":\"Ingen resultater blev fundet\"}");

/***/ }),

/***/ "./res/locales/de/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/de/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"de\",\"@@context\":\"Erweiterung ExtensionsPanel\",\"Viewer Extensions List\":\"Viewer-Erweiterungsliste\",\"Search\":\"Suchen\",\"No results found\":\"Keine Ergebnisse gefunden\"}");

/***/ }),

/***/ "./res/locales/en-GB/nobundle-ExtensionsPanel.loc.json":
/*!*************************************************************!*\
  !*** ./res/locales/en-GB/nobundle-ExtensionsPanel.loc.json ***!
  \*************************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"en\",\"@@context\":\"ExtensionsPanel Extension\",\"Viewer Extensions List\":\"Viewer Extensions List\",\"Search\":\"Search\",\"No results found\":\"No results found\"}");

/***/ }),

/***/ "./res/locales/en/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/en/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"en\",\"@@context\":\"ExtensionsPanel Extension\",\"Viewer Extensions List\":\"Viewer Extensions List\",\"Search\":\"Search\",\"No results found\":\"No results found\"}");

/***/ }),

/***/ "./res/locales/es/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/es/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"es\",\"@@context\":\"Extensión ExtensionsPanel\",\"Viewer Extensions List\":\"Lista de extensiones del visor\",\"Search\":\"Buscar\",\"No results found\":\"No se han encontrado resultados.\"}");

/***/ }),

/***/ "./res/locales/fr-CA/nobundle-ExtensionsPanel.loc.json":
/*!*************************************************************!*\
  !*** ./res/locales/fr-CA/nobundle-ExtensionsPanel.loc.json ***!
  \*************************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr-CA\",\"@@context\":\"Extension ExtensionsPanel\",\"Viewer Extensions List\":\"Liste des extensions du visualiseur\",\"Search\":\"Rechercher\",\"No results found\":\"Aucun résultat trouvé\"}");

/***/ }),

/***/ "./res/locales/fr/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/fr/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr\",\"@@context\":\"Extension ExtensionsPanel\",\"Viewer Extensions List\":\"Liste des extensions de la visionneuse\",\"Search\":\"Rechercher\",\"No results found\":\"Aucun résultat trouvé\"}");

/***/ }),

/***/ "./res/locales/it/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/it/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"it\",\"@@context\":\"Estensione ExtensionsPanel\",\"Viewer Extensions List\":\"Elenco estensioni visualizzatore\",\"Search\":\"Cerca\",\"No results found\":\"Nessun risultato trovato\"}");

/***/ }),

/***/ "./res/locales/ja/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/ja/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ja\",\"@@context\":\"ExtensionsPanel エクステンション\",\"Viewer Extensions List\":\"ビューア エクステンション リスト\",\"Search\":\"検索\",\"No results found\":\"結果はありません\"}");

/***/ }),

/***/ "./res/locales/ko/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/ko/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ko\",\"@@context\":\"ExtensionsPanel 확장\",\"Viewer Extensions List\":\"뷰어 확장 리스트\",\"Search\":\"검색\",\"No results found\":\"결과를 찾을 수 없음\"}");

/***/ }),

/***/ "./res/locales/nl/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/nl/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"nl\",\"@@context\":\"ExtensionsPanel-extensie\",\"Viewer Extensions List\":\"Extensielijst viewer\",\"Search\":\"Zoeken\",\"No results found\":\"Geen resultaten gevonden\"}");

/***/ }),

/***/ "./res/locales/no/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/no/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"no\",\"@@context\":\"ExtensionsPanel Filforlengelse\",\"Viewer Extensions List\":\"Visning av liste over filutvidelser\",\"Search\":\"Søk\",\"No results found\":\"Fant ingen resultater\"}");

/***/ }),

/***/ "./res/locales/pl/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/pl/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pl\",\"@@context\":\"Rozszerzenie ExtensionsPanel\",\"Viewer Extensions List\":\"Lista rozszerzeń przeglądarki\",\"Search\":\"Szukaj\",\"No results found\":\"Nie znaleziono wyników\"}");

/***/ }),

/***/ "./res/locales/pt-BR/nobundle-ExtensionsPanel.loc.json":
/*!*************************************************************!*\
  !*** ./res/locales/pt-BR/nobundle-ExtensionsPanel.loc.json ***!
  \*************************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pt\",\"@@context\":\"Extensão ExtensionsPanel\",\"Viewer Extensions List\":\"Lista de extensões do visualizador\",\"Search\":\"Pesquisar\",\"No results found\":\"Nenhum resultado encontrado\"}");

/***/ }),

/***/ "./res/locales/ru/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/ru/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ru\",\"@@context\":\"Расширение ExtensionsPanel\",\"Viewer Extensions List\":\"Список расширений средства просмотра\",\"Search\":\"Поиск\",\"No results found\":\"Нет результатов поиска\"}");

/***/ }),

/***/ "./res/locales/sv/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/sv/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"sv\",\"@@context\":\"ExtensionsPanel-tillägg\",\"Viewer Extensions List\":\"Lista över visningsprogrammets tillägg\",\"Search\":\"Sök\",\"No results found\":\"Inga resultat hittades\"}");

/***/ }),

/***/ "./res/locales/tr/nobundle-ExtensionsPanel.loc.json":
/*!**********************************************************!*\
  !*** ./res/locales/tr/nobundle-ExtensionsPanel.loc.json ***!
  \**********************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"tr\",\"@@context\":\"ExtensionsPanel Uzantısı\",\"Viewer Extensions List\":\"Görüntüleyici Uzantıları Listesi\",\"Search\":\"Arama\",\"No results found\":\"Sonuç bulunamadı\"}");

/***/ }),

/***/ "./res/locales/zh-HANS/nobundle-ExtensionsPanel.loc.json":
/*!***************************************************************!*\
  !*** ./res/locales/zh-HANS/nobundle-ExtensionsPanel.loc.json ***!
  \***************************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hans\",\"@@context\":\"ExtensionsPanel 扩展\",\"Viewer Extensions List\":\"查看器扩展列表\",\"Search\":\"搜索\",\"No results found\":\"未找到结果\"}");

/***/ }),

/***/ "./res/locales/zh-HANT/nobundle-ExtensionsPanel.loc.json":
/*!***************************************************************!*\
  !*** ./res/locales/zh-HANT/nobundle-ExtensionsPanel.loc.json ***!
  \***************************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hant\",\"@@context\":\"ExtensionsPanel 延伸\",\"Viewer Extensions List\":\"檢視器延伸清單\",\"Search\":\"搜尋\",\"No results found\":\"找不到任何結果\"}");

/***/ }),

/***/ "./res/locales/zh-HK/nobundle-ExtensionsPanel.loc.json":
/*!*************************************************************!*\
  !*** ./res/locales/zh-HK/nobundle-ExtensionsPanel.loc.json ***!
  \*************************************************************/
/*! exports provided: @@locale, @@context, Viewer Extensions List, Search, No results found, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-hk\",\"@@context\":\"ExtensionsPanel 擴充功能\",\"Viewer Extensions List\":\"檢視器擴充功能清單\",\"Search\":\"搜尋\",\"No results found\":\"找不到任何結果\"}");

/***/ })

/******/ });
//# sourceMappingURL=ExtensionsPanel.js.map